import type { Metadata } from "next";
// import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import "./globals.css";
import 'katex/dist/katex.min.css'; 
// import NavBar from "@/components/NavBar"
import Providers from "@/components/Providers";

import "react-loading-skeleton/dist/skeleton.css"

// const inter = Inter({ subsets: ['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='light'>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/rwc2ror.css" />
      </head>
      <Providers>
        <body
          className={cn('min-h-screen font-sans antialiased bg-white'
          )}>
          {/* NavBar removed from global layout */}
          {children}
        </body>
      </Providers>
    </html>
  );
}
